#!/usr/bin/env bash
# mise description="run end-to-end tests"
# mise alias="e"
# mise depends=["build"]

set -euo pipefail

export RUST_TEST_THREADS=1

if [[ "${1:-all}" == all ]]; then
  ./e2e/run_all_tests
else
  FILES="$(fd "$1" e2e/)"
  for FILE in $FILES; do
    ./e2e/run_test "$FILE"
  done
fi
